#cloud-config
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - htop
  - jq
  - ufw
  - iotop
  - net-tools
  - iputils-ping
  - nano
  - tree

runcmd:
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw default deny incoming
  - ufw default allow outgoing
  - echo "y" | ufw enable
  - systemctl restart ufw

users:
  - name: app
    shell: /bin/bash
    sudo: false
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFfmTNW2LOAcOyaBHLvcqvKYn9IiQQBDPItSn745oqhO
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAOGTAZei/8qMu6DhXrtzrB4AE55nRQ+6p4LlT9U7H1R
  - name: root
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFfmTNW2LOAcOyaBHLvcqvKYn9IiQQBDPItSn745oqhO
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAOGTAZei/8qMu6DhXrtzrB4AE55nRQ+6p4LlT9U7H1R 